baseURL = 'https://zhangjian10.github.io/'
languageCode = 'zh-cn'
title = '博客'
theme = 'nostyleplease'

[params]
thumbnail = true
paginate = 10
  [params.theme_config]
    back_home_text = "首页"

[services]
  [services.googleAnalytics]
    ID = 'G-F42FK67S0N'
